### ISSUE TITLE
Incident does not close after Service gets restarted

### ISSUE THREAD

**Issue by philhub82** [newrelic/nri-winservices#104]
If I get an Alarm from this NRQL condition, it stays open even if the Service starts again.

FROM Metric SELECT count(*) WHERE windowsService.startMode='auto' AND windowsService.state IS NOT NULL AND windowsService.state !='running' FACET  windowsService.entityName, windowsService.hostname , windowsService.name, windowsService.state, windowsService.startMode

For me it looks like the Service has a new ID and does not correspond to the Service that was stopped.

**Comment by carlossscastro** [comment]
Hi @philhub82,

Apologies for the delay in answering this. I'm closing this one out, since it seems our Technical Support got that sorted out for you.

Rg,
