### ISSUE TITLE
Clarify which version the docs apply to

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-winservices#105]
As reported [here (internal link)](https://newrelic.slack.com/archives/CP2EWSX7C/p1631666495154700), some users of the previous beta release are getting confused since the contents of the docs page no longer reflect the data structure and sample names of the old integration.

We should make this more evident in the docs, clarifying to which version this applies in a visible Callout.

**Comment by mangulonr** [comment]
I've done this PR so we can consider this ticket as closed.

https://github.com/newrelic/docs-website/pull/3948
https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/windows-services-integration/
