### ISSUE TITLE
Services with "state" NULL

### ISSUE THREAD

**Issue by philhub82** [newrelic/nri-winservices#111]
Services showing up with "state=NULL" instead of "running"
FROM Metric SELECT count(*) WHERE start_mode='auto' FACET service_name, hostname, state

**Comment by paologallinaharbur** [comment]
The integration is scraping the prometheus output from a community exporter. 
 - Does it happen from time to time or is it an issue that happens continuously?
 - Are you running the last version of the integration?

It would help us with the troubleshooting if you could share with us the output of such exporter while the integration is reporting NULL state for a specific service. The default location is "127.0.0.1:9182/metrics"
 If that output has sensitive data could you sanitize it or open a ticket?

@alvarocabanas @carlossscastro

**Comment by philhub82** [comment]
I had contact with support and they told me the following:
count() and uniqueCount() will never return a value of 0 (explained here: https://discuss.newrelic.com/t/relic-solution-how-can-i-figure-out-when-to-use-gap-filling-and-loss-of-signal/120401).
So the easiest is, to configure a LoS (Loss of Signal) to close Incidents that do not report the error anymore.
I tried it and it worked fine in my case.
