### ISSUE TITLE
Not able to see the services-metrics in new relic after changing the Config file.

### ISSUE THREAD

**Issue by DevendrasinghLabana** [newrelic/nri-winservices#131]
After changing the winservices-config.yml file, I am not able to see the services-metrics in new relic.

I am trying to enable window service integration, by including the services in the winservices-config.yml file.

##Expected Outcome
After changing the winservices-config.yml file, the metric(state) of these services-
HyS9CALC_epmsystem1_PLN
HyS9EPMADataSynchronizer_epmsystem1_PLN 
HyS9EPMAServer_epmsystem1_PLN
HyS9EPMAWebTier_epmsystem1_PLN
HyS9Planning_epmsystem1_PLN
HyS9RMIRegistry_epmsystem1_PLN
should reflect in new relic

Refer- NRDIAG FILE
[Hyperion.zip](https://github.com/newrelic/nri-winservices/files/9038239/Hyperion.zip)

## Steps to Reproduce

1. Stop the Infra Agent.
2. Edited the Winservices-config.yml file.
-------------------config file--------------------------------------
integrations:
  - name: nri-winservices
    config:
      exporter_bind_address: 127.0.0.1
      exporter_bind_port: 9182
      include_matching_entities:
        windowsService.name:
          - "HyS9CALC_epmsystem1_PLN"	
	  - "HyS9EPMADataSynchronizer_epmsystem1_PLN"
	  - "HyS9EPMAServer_epmsystem1_PLN"
	  - "HyS9EPMAWebTier_epmsystem1_PLN"
	  - "HyS9Planning_epmsystem1_PLN"
	  - "HyS9RMIRegistry_epmsystem1_PLN"
            
      scrape_interval: 30s
    timeout: 60s
3. Restarted the Infra agent.

--------------------------------------------------------------------------

"Platform": "Microsoft Windows Server 2012 R2 Standard",
"PlatformFamily": "Server",
"PlatformVersion": "6.3.9600 Build 9600",
"agent_version= 1.20.7"

## Additional context
New relic Support Case #00048222
Note- Kindly refer the Nrdiag file and help me on how to enable this integration in new relic.

**Comment by davidgit** [comment]
I'm closing this because an internal support ticket has been created to address the case
