### ISSUE TITLE
Windows Services integration not working

### ISSUE THREAD

**Issue by srafique2022** [newrelic/nri-winservices#137]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
Issue where windows services integration is not working as expected. 
## Description
time="2022-08-26T17:46:19-04:00" level=warning msg="can't load integrations file. This may happen if you are editing a file and saving intermediate changes" component=integrations.config.Loader dir="C:\\Program Files\\New Relic\\newrelic-infra\\integrations.d" error="yaml: line 6: did not find expected key" file=winservices-config.yml

Related support case: https://newrelic-neworg.lightning.force.com/lightning/r/Case/5008W00000tBO06QAG/view

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

## [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by gsanchezgavier** [comment]
Hi ,I'm closing this ticket since is being tracked by internal support.
