### ISSUE TITLE
Agent Not Reporting Service Status

### ISSUE THREAD

**Issue by Tomthi** [newrelic/nri-winservices#43]
[NOTE]: # I updated the infrastructure agent and I am not able to find the status of the service I'm trying to monitor. 

## Description
The infra agent  was updated and the windows service name was added to the winservice-config.yml in the 

Section

    include_matching_entities:
        windowsService.name:
            - "MyServiceName"

Restarted the agent service. 

## Expected Behavior

I should be able to run the query to at lest see the status of the service 

```SELECT count(*) FROM Metric WHERE metricName = 'windowsService.service.state' AND windowsService.state = 'running' AND windowsService.name = 'MyServiceName' FACET windowsService.entityName```

 Also in the cart builder, this does not seem to be available.  Predictive text isn't working or recognizing windosSerivce

```FROM Metric SELECT windowsService```

## [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

None

## Steps to Reproduce

1. Update Agent
2. edit winservice-config.yml to include service name.
3. Restart infra agent service
4. Query dataset

## Your Environment
AWS ec2 instances on Windows 2016

**Comment by paologallinaharbur** [comment]
Hello Tomthi, are you part of the beta program? If not I believe your issue is similar to #44  

On the other hand, if you joined and still you have issues:
 - at least one service is reported?
 - can you retrieve the logs in verbose mode and share them?

**Comment by gsanchezgavier** [comment]
@Tomthi  let us know if the issue persist
