### ISSUE TITLE
Service Status not getting Reported to NewRelic

### ISSUE THREAD

**Issue by Santu439** [newrelic/nri-winservices#47]
Hi Team,

We have tried integrate this windows services monitoring however no data reported on NewRelic.

I see no errors apart from this on logs. Can you please assist?

time="2020-11-19T03:37:00-05:00" level=warning msg="can't parse v4 integration output" component=integrations.emitter.Emitter error="integration protocol version 4 is not enabled" 

Please find attached config & log files
[newrelic-infra.log](https://github.com/newrelic/nri-winservices/files/5566217/newrelic-infra.log)
[newrelic-infra_1.log](https://github.com/newrelic/nri-winservices/files/5566218/newrelic-infra_1.log)
[winservices-config_yml.txt](https://github.com/newrelic/nri-winservices/files/5566226/winservices-config_yml.txt)

**Comment by gsanchezgavier** [comment]
Hi @Santu439  is the account you are using part of the Beta Program? if not that is the problem. This integration would not work for now if you are not part of the beta program.

**Comment by Santu439** [comment]
Hi @gsanchezgavier , we do use some of the Beta modules like incident workflows, workloads, etc., so I believe we are part of Beta program.

Please advise if there is a way to check and get it enabled for our account?

**Comment by ikavanaghNR** [comment]
Hi @Santu439 if you provide your account number, we can give you access.

**Comment by Santu439** [comment]
Hi Ian, thanks for your help on our other mail thread. After you updated the feature flag, Its working now

**Comment by Santu439** [comment]
its fixed
