### ISSUE TITLE
Integration Not Recovering After Error

### ISSUE THREAD

**Issue by CharlieWinters** [newrelic/nri-winservices#65]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
The integration is being used on a Microsoft Windows Server 2016 Datacenter host. At certain times the host seems to get maxed out on resources, i.e. we get CPU, load average, disk utilisation spikes, and then the integration appears to stop sending samples.

The issue is that the integration doesn't appear to recover until the Infrastructure agent is restarted.

## Description
[NOTE]: # ( Describe the problem you're encountering. )
Some internal info has been outlined in support ticket #448676

We get errors in the logs like:
time="2021-02-27T08:21:39Z" level=warning msg="integration exited with error state" component=integrations.runner.Runner error="exit status 2" integration_name=com.newrelic.winservices stderr="(last 10 lines out of 7476): ....

and a message below for the monitored services:
time="2021-02-28T15:01:42Z" level=info msg="Removing inventory cache" agentEntityIDChanged=false component=PatchSender entityKey="<HOSTNAME>:<SERVICENAME>" offlineTime=24h0m0s

[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
I would expect the integration to recover once resources become available again.

## [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )
Max out resources on the host, observe windows services samples not being sent, integration does not recover.

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )
Microsoft Windows Server 2016

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )
I've built a troubleshooting dashboard that is detailed in support ticket: #448676.

**Comment by CharlieWinters** [comment]
Thanks @roobre 

We've got a support ticket open if you have access, #448676

Otherwise here's the rest of the log: 

time="2021-02-27T08:21:39Z" level=warning msg="integration exited with error state" component=integrations.runner.Runner error="exit status 2" integration_name=com.newrelic.winservices stderr="(last 10 lines out of 7476): [INFO] exporter msg=Build context (go=go1.14.4, user=fv-az104\\runneradmin@fv-az104, date=20200617-17:40:48) source=exporter.go:352\n[INFO] exporter msg=Starting server on 127.0.0.1:9182 source=exporter.go:355\n[INFO] exporter msg=Enabled collectors: service, cs source=exporter.go:326\n[INFO] exporter msg=Starting windows_exporter (version=0.13.0-10-gc9f1e50-dirty, branch=HEAD, revision=c9f1e5068a267aeb3e8cff47bc5323cbc050055a) source=exporter.go:351\n[INFO] exporter msg=Build context (go=go1.14.4, user=fv-az104\\runneradmin@fv-az104, date=20200617-17:40:48) source=exporter.go:352\n[INFO] exporter msg=Starting server on 127.0.0.1:9182 source=exporter.go:355\n[INFO] exporter msg=Enabled collectors: service, cs source=exporter.go:326\n[INFO] exporter msg=Starting windows_exporter (version=0.13.0-10-gc9f1e50-dirty, branch=HEAD, revision=c9f1e5068a267aeb3e8cff47bc5323cbc050055a) source=exporter.go:351\n[INFO] exporter msg=Build context (go=go1.14.4, user=fv-az104\\runneradmin@fv-az104, date=20200617-17:40:48) source=exporter.go:352\n[INFO] exporter msg=Starting server on 127.0.0.1:9182 source=exporter.go:355"

time="2021-02-27T11:37:56Z" level=warning msg="integration exited with error state" component=integrations.runner.Runner error="context canceled" integration_name=com.newrelic.winservices stderr="(last 10 lines out of 52): [INFO] exporter msg=Build context (go=go1.14.4, user=fv-az104\\runneradmin@fv-az104, date=20200617-17:40:48) source=exporter.go:352\n[INFO] exporter msg=Starting server on 127.0.0.1:9182 source=exporter.go:355\n[INFO] exporter msg=Enabled collectors: service, cs source=exporter.go:326\n[INFO] exporter msg=Starting windows_exporter (version=0.13.0-10-gc9f1e50-dirty, branch=HEAD, revision=c9f1e5068a267aeb3e8cff47bc5323cbc050055a) source=exporter.go:351\n[INFO] exporter msg=Build context (go=go1.14.4, user=fv-az104\\runneradmin@fv-az104, date=20200617-17:40:48) source=exporter.go:352\n[INFO] exporter msg=Starting server on 127.0.0.1:9182 source=exporter.go:355\n[INFO] exporter msg=Enabled collectors: service, cs source=exporter.go:326\n[INFO] exporter msg=Starting windows_exporter (version=0.13.0-10-gc9f1e50-dirty, branch=HEAD, revision=c9f1e5068a267aeb3e8cff47bc5323cbc050055a) source=exporter.go:351\n[INFO] exporter msg=Build context (go=go1.14.4, user=fv-az104\\runneradmin@fv-az104, date=20200617-17:40:48) source=exporter.go:352\n[INFO] exporter msg=Starting server on 127.0.0.1:9182 source=exporter.go:355"

**Comment by roobre** [comment]
Thanks for raising this. Since you already have a ticket open, the support/product team will follow from that, as it is our preferred method for managing issues that require troubleshooting and/or have a big scope.

**Comment by mangulonr** [comment]
> Thanks @roobre
> 
> We've got a support ticket open if you have access, #448676
> 
> Otherwise here's the rest of the log:
> 
> time="2021-02-27T08:21:39Z" level=warning msg="integration exited with error state" component=integrations.runner.Runner error="exit status 2" integration_name=com.newrelic.winservices stderr="(last 10 lines out of 7476): [INFO] exporter msg=Build context (go=go1.14.4, user=fv-az104\runneradmin@fv-az104, date=20200617-17:40:48) source=exporter.go:352\n[INFO] exporter msg=Starting server on 127.0.0.1:9182 source=exporter.go:355\n[INFO] exporter msg=Enabled collectors: service, cs source=exporter.go:326\n[INFO] exporter msg=Starting windows_exporter (version=0.13.0-10-gc9f1e50-dirty, branch=HEAD, revision=c9f1e5068a267aeb3e8cff47bc5323cbc050055a) source=exporter.go:351\n[INFO] exporter msg=Build context (go=go1.14.4, user=fv-az104\runneradmin@fv-az104, date=20200617-17:40:48) source=exporter.go:352\n[INFO] exporter msg=Starting server on 127.0.0.1:9182 source=exporter.go:355\n[INFO] exporter msg=Enabled collectors: service, cs source=exporter.go:326\n[INFO] exporter msg=Starting windows_exporter (version=0.13.0-10-gc9f1e50-dirty, branch=HEAD, revision=c9f1e5068a267aeb3e8cff47bc5323cbc050055a) source=exporter.go:351\n[INFO] exporter msg=Build context (go=go1.14.4, user=fv-az104\runneradmin@fv-az104, date=20200617-17:40:48) source=exporter.go:352\n[INFO] exporter msg=Starting server on 127.0.0.1:9182 source=exporter.go:355"
> 
> time="2021-02-27T11:37:56Z" level=warning msg="integration exited with error state" component=integrations.runner.Runner error="context canceled" integration_name=com.newrelic.winservices stderr="(last 10 lines out of 52): [INFO] exporter msg=Build context (go=go1.14.4, user=fv-az104\runneradmin@fv-az104, date=20200617-17:40:48) source=exporter.go:352\n[INFO] exporter msg=Starting server on 127.0.0.1:9182 source=exporter.go:355\n[INFO] exporter msg=Enabled collectors: service, cs source=exporter.go:326\n[INFO] exporter msg=Starting windows_exporter (version=0.13.0-10-gc9f1e50-dirty, branch=HEAD, revision=c9f1e5068a267aeb3e8cff47bc5323cbc050055a) source=exporter.go:351\n[INFO] exporter msg=Build context (go=go1.14.4, user=fv-az104\runneradmin@fv-az104, date=20200617-17:40:48) source=exporter.go:352\n[INFO] exporter msg=Starting server on 127.0.0.1:9182 source=exporter.go:355\n[INFO] exporter msg=Enabled collectors: service, cs source=exporter.go:326\n[INFO] exporter msg=Starting windows_exporter (version=0.13.0-10-gc9f1e50-dirty, branch=HEAD, revision=c9f1e5068a267aeb3e8cff47bc5323cbc050055a) source=exporter.go:351\n[INFO] exporter msg=Build context (go=go1.14.4, user=fv-az104\runneradmin@fv-az104, date=20200617-17:40:48) source=exporter.go:352\n[INFO] exporter msg=Starting server on 127.0.0.1:9182 source=exporter.go:355"

Hi Charlie

Would you be interesting on be an EAP of our new beta version?
Performance problems because of WMI have been fixed.

If yes, please send me an email to mangulo@newrelic.com

Regards

**Comment by mangulonr** [comment]
Hi

We just released a new open beta version of the [Windows Services integration](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/windows-services-integration/).

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
